### ISSUE TITLE
missing riot-router in package.jason

### ISSUE THREAD

**Issue by miooim** [kysonic/riot-mui-page#1]
Please add riot-router to package.json, webpack build is failing:
$ webpack
Hash: cad59c81e4bf3014ce81
Version: webpack 1.13.0
Time: 4942ms
    Asset    Size  Chunks             Chunk Names
bundle.js  303 kB       0  [emitted]  main
    + 98 hidden modules

ERROR in ./app/router.js
Module not found: Error: Cannot resolve module 'riot-router' in /Users/mishalerman/Private/riot/riot-todo/riot-mui/riot-mui-page/app
 @ ./app/router.js 4:0-22

ERROR in ./app/components/layouts/home-layout.tag
Module not found: Error: Cannot resolve module 'riot-router' in /Users/mishalerman/Private/riot/riot-todo/riot-mui/riot-mui-page/app/components/layouts
 @ ./app/components/layouts/home-layout.tag 10:0-22

ERROR in ./app/components/layouts/basic-layout.tag
Module not found: Error: Cannot resolve module 'riot-router' in /Users/mishalerman/Private/riot/riot-todo/riot-mui/riot-mui-page/app/components/layouts
 @ ./app/components/layouts/basic-layout.tag 9:0-22

**Comment by kysonic** [comment]
@miooim Thanks for your notification! Fixed.
