### ISSUE TITLE
Inconsistent UI for DEMO app

### ISSUE THREAD

**Issue by dimon777** [kysonic/riot-mui-page#2]
http://kysonic.github.io/riot-mui/#buttons

Showed as a:
- page with left vertical section for components in Chrome 
- page with hamburger icon which doesn't show all mui elements in Firefox

**Comment by kysonic** [comment]
@dimon777 Probably it's related to a mobile version of demo page. I think you opened the page in small-size window (<1024px)

**Comment by dimon777** [comment]
thanks @kysonic this was it
